### ISSUE TITLE
quartz_cors v0.7.0 does not work with `quart` v0.19.0

### ISSUE THREAD

**Issue by epwr** [pgjones/quart-cors#6]
The `pyproject.toml` says it supports `quart = ">=0.15"`, however this package does not support quartz 0.19.0. The `v0.19.0` [release notes](https://github.com/pallets/quart/commit/655f0d1b1528f669ab8f2c89ba24d5212eb7cef4) for quart do not mention an API change that seems related, but I'm not sure.

### Minimal Example:

Set up a folder & venv with the following files:

`requirements.txt`
```txt
Quart==0.19.0
quart-cors==0.7.0
```

`main.py`
```python
from quart import Quart
from quart_cors import cors

app = Quart(__name__)
app = cors(app, allow_origin="*", allow_methods="*", allow_headers="*")

@app.route("/")
async def get_status():
    return {"status": "success"}
```

Run:

```sh
pip install -r requirements.txt
python main.py
```

Result:

```
Traceback (most recent call last):
  File "/Users/***/quart_cors_dependency_issue/main.py", line 5, in <module>
    app = cors(app, allow_origin="*", allow_methods="*", allow_headers="*")
  File "/Users/***/quart_cors_dependency_issue/venv/lib/python3.10/site-packages/quart_cors/__init__.py", line 259, in cors
    app_or_blueprint.before_websocket(partial(_before_websocket, allow_origin=allow_origin))
AttributeError: 'Quart' object has no attribute 'before_websocket'. Did you mean: 'handle_websocket'?
```

**Comment by epwr** [comment]
I should note that this worked in quart v0.18.3

**Comment by epwr** [comment]
This has been fixed with quart v0.19.3. Closing.
